// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vcxmkydhpmijzeghmvvi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZjeG1reWRocG1panplZ2htdnZpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTczNTE0MzYsImV4cCI6MjA3MjkyNzQzNn0.SKZlJzhscV7RT__KqPRijdD-AlTrtb78T0EMu5X1WHM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});